### PR TITLE
Files structure

### PR DESCRIPTION
**Pull request by AlexJaneMercer**
Edited the file structure of the site so as not to get lost in the files.
image

### CODE REVIEW

**Comment by Zack-Dx** [comment]
@AlexJaneMercer please update your branch.

**Comment by AlexJaneMercer** [comment]
uno momento

**Comment by AlexJaneMercer** [comment]
@Zack-Dx done

**Comment by Zack-Dx** [comment]
@AlexJaneMercer  Thank YOU! for the contribution. Share love by giving a star to the repo. Merged!

**Pull request merged**
