### PR TITLE
empty note message, scrollbar style, hover on input

### PR DESCRIPTION
**Pull request by UjjwalAggarwal-1**

### CODE REVIEW

**Comment by Zack-Dx** [comment]
@UjjwalAggarwal-1 Hi Ujjwal I'm all ready to merge this but I just want you to change the colour of the empty message and the grammar error in the message. Thanks!

**Comment by UjjwalAggarwal-1** [comment]
what would you like?

**Comment by Zack-Dx** [comment]
> what would you like?

Anything your wish! just not too bright

**Comment by UjjwalAggarwal-1** [comment]
image

current status

**Comment by Zack-Dx** [comment]
> image
> 
> current status

Great! just don't forget to update your branch before committing your changes.

**Comment by UjjwalAggarwal-1** [comment]
done

**Comment by Zack-Dx** [comment]
@UjjwalAggarwal-1 Merged! Thank YOU!

**Comment by Zack-Dx** [comment]
@UjjwalAggarwal-1 Ujjwal there's one issue as you see the updated link, would you like to fix that ? your empty message keeps showing. If yes, throw a new pr. Thanks!

**Comment by UjjwalAggarwal-1** [comment]
did not get what you mean by "updated link", please show>

**Pull request merged**
