### PR TITLE
added edit button and dark mode feature

### PR DESCRIPTION
**Pull request by RibhavKhanna**
I have added edit button and dark mode option. edit button changes the value of the note to the value in text area when clicked.
Please make it hacktoberfest accepted.
image

### CODE REVIEW

**Comment by Zack-Dx** [comment]
@RibhavKhanna I think dark mode is correct but make sure the edit button functionality works. It's not working for now

**Comment by RibhavKhanna** [comment]
@Zack-Dx can you please elaborate the issue, because it is working on my side.

https://user-images.githubusercontent.com/101007097/197850478-5d1033eb-1a96-44ca-a154-03b9dbd04770.mp4

**Comment by RibhavKhanna** [comment]
@Zack-Dx edit button is working fine for me as you can see in the video. If possible, could you please send me a photo or video regarding the issue. Thanks.

**Comment by Zack-Dx** [comment]
@RibhavKhanna Ribhav kindly throw a new pr as this holds conflicts too. I'll merge that. Thanks!

**Pull request closed without merging**
