### PR TITLE
Added the "search note" pallet in the navbar, and added a 'confirm' button for delete note.

### PR DESCRIPTION
**Pull request by divyang9575**
Please merge the pull request.

### CODE REVIEW

**Comment by Zack-Dx** [comment]
@divyang9575 Please update your forked branch.

**Comment by Zack-Dx** [comment]
@divyang9575 please update your forked branch.

**Comment by divyang9575** [comment]
Ok please check weather the conflict has been solved or not.

**Comment by Zack-Dx** [comment]
@divyang9575 It's breaking the responsiveness totally.

**Pull request closed without merging**
