### PR TITLE
Search bug resolved

### LINKED ISSUE #110: Bug: The search is not working
The search is not currently working. Whatever text is written in search, all the notes become hidden.
Also, on removing all content from search bar, the dimensions of the notes change from the dimensions

### PR DESCRIPTION
**Pull request by malay5**
The issue with search, where it does not show any results has been resolved and the changing of notes dimensions has been resolved. 
Closes #110

### CODE REVIEW

**Comment by malay5** [comment]
Please close this PR under hacktoberfest22

**Comment by Zack-Dx** [comment]
@malay5  Thank YOU! for the contribution. Share love by giving a star to the repo. Merged!

**Comment by malay5** [comment]
Hey @Zack-Dx , the contribution is not showing under my hacktober profile. Can it be because PR was merged and then labels are added?

**Comment by malay5** [comment]
Thank you for maintaining such a great project!

**Pull request merged**
