### PR TITLE
welcome message added

### PR DESCRIPTION
**Pull request by qashifpeer**
I have added welcome message on top of input , plz review

### CODE REVIEW

**Comment by qashifpeer** [comment]
Please add hacktoberfest tag

**Comment by Zack-Dx** [comment]
@qashifpeer Try to change the text colour for dark mode as it's not visible in it.

**Comment by qashifpeer** [comment]
changed the text color in dark mode

**Comment by Zack-Dx** [comment]
@qashifpeer Thank YOU! for the contribution. Share love by giving a star to the repo. Merged!

**Comment by qashifpeer** [comment]
Could you tag it hacktoberfest plz

**Pull request merged**
