### PR TITLE
Enhanced the UI, added "search note" pallet.

### PR DESCRIPTION
**Pull request by divyang9575**
Please merge the pull request and add hacktoberfest

### CODE REVIEW

**Comment by Zack-Dx** [comment]
@divyang9575 Already told you it's breaking the responsiveness.

**Comment by divyang9575** [comment]
todolist
todo2

But I made it responsive now.

**Comment by Zack-Dx** [comment]
> todolist
> 
> todo2
> 
> But I made it responsive now.

Check for ipads!

**Comment by divyang9575** [comment]
todoipad
todoipadmini

It is fixed for ipads also and if the footer is creating the issue then that is not under my PR, someone else created the footer.

**Comment by Zack-Dx** [comment]
@divyang9575 This isn't a valid reason to escape changes u're contributing to a codebase with a new functionality. So, if earlier footer was present then it's issue from your side because your functionality doesn't match with the components. You just can't put like this, then if it's like so then without your search bar that would be fine too.

**Comment by divyang9575** [comment]
I'm not escaping from any issue but I cleared the issue as you can see in the screenshot the footer is working fine in ipad also, so I'm unable to understand exactly which issue are you talking about.

**Comment by divyang9575** [comment]
before

 Now as you can in this, the footer before my code addition is working exactly the same which means my code didn't added any error to the footer's responsiveness. So I'm unable to understand what the issue exactly is ??

**Comment by divyang9575** [comment]
And when I said that someone else has created the footer, I meant that I didn't even the touched the footer code and it is working completely in the same way before and after my code addition, you can check both the codes yourself as I have checked it multiple times. And still if you are not satisfied than please guide me through that what else I can do.

**Comment by Zack-Dx** [comment]
@divyang9575 leave that issue I'll fix it myself only. I don't your efforts and time to get wasted. I'm happily merging your contribution. Thanks for the addons. Have a great day.

**Comment by Zack-Dx** [comment]
> @divyang9575 leave that issue I'll fix it myself only. I don't  want your efforts and time to get wasted. I'm happily merging your contribution. Thanks for the addons. Have a great day.

**Comment by divyang9575** [comment]
Thank you so much Sir, means a lot. And I'm really sorry if I'm unable to fulfill the demands, I'm a beginner in this field.

**Comment by Zack-Dx** [comment]
> Thank you so much Sir, means a lot. And I'm really sorry if I'm unable to fulfill the demands, I'm a beginner in this field. Can you please add the hacktoberfest tag I request you.

Oh damn I forgot to update the labels thanks for the reminder, you will learn day-2-day and change is a continuous process 👍🏻

**Pull request merged**
