### PR TITLE
Added Red theme

### PR DESCRIPTION
**Pull request by RiyaBhaskar12**
I've added a new color theme. This theme can be added into website by adding a toggle button to switch b/w colors as convenient. We can add many more themes in future which may include pictures too to make it more engaging for users.

### CODE REVIEW

**Comment by Zack-Dx** [comment]
@RiyaBhaskar12 Hey Riya! can u please update your forked branch and then commit.

**Comment by RiyaBhaskar12** [comment]
I've updated

**Comment by Zack-Dx** [comment]
> I've updated

Can u share the screenshots of your theme?

**Comment by RiyaBhaskar12** [comment]
i've added the samples
please check

**Comment by RiyaBhaskar12** [comment]
resolved the conflicts too

**Comment by Zack-Dx** [comment]
> resolved the conflicts too

@RiyaBhaskar12 I checked but can u tell me how u gonna toggle that? because as per default the theme is on lavender side!

**Comment by RiyaBhaskar12** [comment]
Yes, A button needs to be added to switch b/w the themes #62 
[https://annoyingsubmitbutton.netlify.app/](url)
check for this, there can be different themes according to likeliness of user

**Comment by RiyaBhaskar12** [comment]
Check this out to get an idea:
https://github.com/RiyaBhaskar12/Annoying-submit-button-Task1/tree/main

**Comment by Zack-Dx** [comment]
> Yes, A button needs to be added to switch b/w the themes #62 [https://annoyingsubmitbutton.netlify.app/](url) check for this, there can be different themes according to likeliness of user

You wanna add that button?

**Comment by RiyaBhaskar12** [comment]
I won't be able to add that, so I'm not working on  Please mark my contribution as completed.

**Pull request closed without merging**
