### PR TITLE
add var color

### PR DESCRIPTION
**Pull request by nadya12082012**

### CODE REVIEW

**Comment by Zack-Dx** [comment]
@nadya12082012 ss and please update your branch.

**Comment by nadya12082012** [comment]
done, everything is updated

**Comment by Zack-Dx** [comment]
> done, everything is updated

try doing once more.

**Comment by nadya12082012** [comment]
updated again

**Comment by Zack-Dx** [comment]
@nadya12082012 please throw a new pr this's having some issues.

**Pull request closed without merging**
