### PR TITLE
dark mode

### PR DESCRIPTION
**Pull request by khushigarg1**

### CODE REVIEW

**Comment by Zack-Dx** [comment]
@khushigarg1 Hi Khushi can u please update your forked branch cause this holds conflicts.

**Comment by khushigarg1** [comment]
Yes I had done.

**Comment by Zack-Dx** [comment]
@khushigarg1 Amazing Work! but can u change the light colour to bit lavender as per theme and dark one to kinda blue and throw a new pr. Thanks!

**Comment by Zack-Dx** [comment]
@khushigarg1 I need to revert this for a issue on dual dark modes. If u want to add this as it is try to remove the one with the button.

**Comment by khushigarg1** [comment]
Thank You!!

**Comment by khushigarg1** [comment]
Okay sure, I will try.

**Pull request merged**
