### PR TITLE
Added favicon.ico file and icon to header title

### PR DESCRIPTION
**Pull request by michelle-santiago**

### CODE REVIEW

**Comment by Zack-Dx** [comment]
@michelle-santiago please update your forked branch

**Comment by michelle-santiago** [comment]
> @michelle-santiago please update your forked branch

Done updating ty

**Comment by Zack-Dx** [comment]
> > @michelle-santiago please update your forked branch
> 
> Done updating ty

@michelle-santiago  Thank YOU! for the contribution. Share love by giving a star to the repo. Merged! btw what's that in your profile pic?

**Comment by michelle-santiago** [comment]
Thank you! It's called chibi-totoro, art by pix brix. Here's the link https://www.pinterest.ph/pin/my-neighbour-totoro-ghibli-pixel-art-pattern--757871443542880050/. I like ghibli characters, they are adorable!(⁠◍⁠•⁠ᴗ⁠•⁠◍⁠)

**Comment by Zack-Dx** [comment]
@michelle-santiago Amazing one! Thanks for sharing.

**Pull request merged**
