### PR TITLE
MernToDo

### PR DESCRIPTION
**Pull request by Znoy108x**
i have completed  it  by implementing these features :
- login - register
- private notes
- delete / restore / pin / complete functionality
- interactive layout
- tag filters

### CODE REVIEW

**Comment by Zack-Dx** [comment]
@Znoy108x app doesn't start.

**Comment by Znoy108x** [comment]
@Zack-Dx  you have to paste the credentials of your db in your backend/db.js file i have mentioned it in readme.md

**Comment by Zack-Dx** [comment]
@Znoy108x but this is totally different project I don't see any changes based on repo. This's like u're pushing an external project to change the repo itself.

**Comment by Znoy108x** [comment]
@Zack-Dx no ! i implemented what i told you  and your repo was based on to do app . what i have implemented is also a to do app but a advanced version of it

**Comment by Zack-Dx** [comment]
> @Zack-Dx no ! i implemented what i told you and your repo was based on to do app . what i have implemented is also a to do app but a advanced version of it

Sorry to say, but people can throw a pr having Todos with other tech stacks too because your pr doesn't holds any context of the main repo. If u say u're using a tech stack then it's better to land on the page of Blueberry Keep Notes with a lavender vibe. I don't find such things in your committed branch. One thing can be done in many ways that doesn't mean they are same.

**Pull request closed without merging**
