### PR TITLE
Sidowxyz

### PR DESCRIPTION
**Pull request by sidowxyz**
I Set the Logo as a Link to Homepage, I also change the welcome message to TO-DO LIST
Please accept

### CODE REVIEW

**Comment by sidowxyz** [comment]
please accept my pull request I Set the Logo as a Link to Homepage, I also change the welcome message to TO-DO LIST
Please accept

**Comment by Zack-Dx** [comment]
@sidowxyz Hi Sid can u please update your forked branch because this one has conflicts.

**Comment by sidowxyz** [comment]
Okay 👍

**Comment by sidowxyz** [comment]
How do I update

**Comment by Zack-Dx** [comment]
@sidowxyz I reverted one pr so now it's same. Anyways, thank you for the contribution. Share love by giving a star to the repo. Merged!

**Pull request merged**
