### PR TITLE
edit and dark mode theme button added

### PR DESCRIPTION
**Pull request by RibhavKhanna**
@Zack-Dx I have added edit and dark mode buttons please merge it and make it hactoberfest accepted.

### CODE REVIEW

**Comment by Zack-Dx** [comment]
@RibhavKhanna 
Screenshot 2022-10-26 at 9 38 31 AM
The colours aren't matching at all please fix so that the text would become visible too.

**Comment by RibhavKhanna** [comment]
@Zack-Dx, I have changed text color of "Blueberry Keep" in light mode. Please review.
image

**Comment by Zack-Dx** [comment]
@RibhavKhanna Much better than before! Just fix the edit to 'Edit' and make the light theme background lavender as per per theme.

**Comment by RibhavKhanna** [comment]
@Zack-Dx done!
image

**Comment by Zack-Dx** [comment]
@RibhavKhanna Thanks for your contribution & understanding, spread love by giving a star to the repo. Merged!

**Pull request merged**
