### PR TITLE
Moving js code from index.html to a separate ja file

### PR DESCRIPTION
**Pull request by B0r1Koff**
@Zack-Dx js code from index.html has been moved to a separate js file

### CODE REVIEW

**Comment by Zack-Dx** [comment]
@B0r1Koff please update ur forked branch.

**Comment by Zack-Dx** [comment]
> > @B0r1Koff please update ur forked branch.
> 
> @Zack-Dx seems to be ok now

Not yet.

**Comment by B0r1Koff** [comment]
> > > @B0r1Koff please update ur forked branch.
> > 
> > 
> > @Zack-Dx seems to be ok now
> 
> Not yet.

@Zack-Dx  and now?

**Comment by Zack-Dx** [comment]
> > > > @B0r1Koff please update ur forked branch.
> > > 
> > > 
> > > @Zack-Dx seems to be ok now
> > 
> > 
> > Not yet.
> 
> @Zack-Dx and now?

once more. Do it again

**Comment by B0r1Koff** [comment]
> > > > > @B0r1Koff please update ur forked branch.
> > > > 
> > > > 
> > > > @Zack-Dx seems to be ok now
> > > 
> > > 
> > > Not yet.
> > 
> > 
> > @Zack-Dx and now?
> 
> once more. Do it again

@Zack-Dx Ok I did it again

**Comment by Zack-Dx** [comment]
@B0r1Koff  Thank YOU! for the contribution. Share love by giving a star to the repo. Merged!

**Pull request merged**
