### PR TITLE
added animated bg

### PR DESCRIPTION
**Pull request by FireNdIce3**

### CODE REVIEW

**Comment by Zack-Dx** [comment]
@FireNdIce3 Can u please change it into bubbles and decrease the opacity a bit.

**Comment by FireNdIce3** [comment]
Okay!

**Comment by FireNdIce3** [comment]
Done !!

**Comment by Zack-Dx** [comment]
@FireNdIce3 Hi Fire Great work. Thank YOU! for the contribution. Share love by giving a star to the repo. Merged!

**Comment by Zack-Dx** [comment]
@FireNdIce3  Fire I actually need to revert this as we can't input in the textarea so fix your z-index.

**Pull request merged**
