### PR TITLE
storage refactoring: will allow us to store more fields in it

### PR DESCRIPTION
**Pull request by halavasty**
1. storage stores notes as objects, not strings
2. added new field - date
3. fixed sweetalert2 for 'delete all'

### CODE REVIEW

**Comment by Zack-Dx** [comment]
@halavasty please update your forked branch & can you tell? wdym by your 1st point about object thing? it's already stored in string format.

**Comment by halavasty** [comment]
now notes are stored as an array of strings - ['note1', 'note2', 'note3']
but after update they will be stored as an array of objects - [ {id: 123123123, date: 123123123, value: 'note1'}, {id: 123123124, date: 123123124, value: 'note2'},  {id: 123123125, date: 123123125, value: 'note3'} ]

```js
// code excerpt
{
      id: new Date().getTime(),
      date: new Date().getTime(),
      value: addNote.value,
}
```

**Comment by halavasty** [comment]
branch is ready @Zack-Dx

**Comment by halavasty** [comment]
it is worth merging this branch faster, since the project is not working now.
message.js file was added not in JS folder. and in index.html invalid paths to js files
this PR contains fix @Zack-Dx

**Comment by halavasty** [comment]
@Zack-Dx Thank you for your efforts! it helps a lot of people to become better

**Comment by Zack-Dx** [comment]
> @Zack-Dx Thank you for your efforts! it helps a lot of people to become better

@halavasty you got discord?

**Comment by halavasty** [comment]
I found this project there 😌 in the festival group

**Comment by Zack-Dx** [comment]
> I found this project there 😌 in the festival group

that's great. So, u don't use discord?

**Pull request merged**
